In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [2]:
df_train = pd.read_csv('D:/Data/tmlcc-2021/train_clean_no_outlier_01-10.csv')
df_feat_train = pd.read_csv('D:/Code/tcml/train_mnc_metal.csv')
df_pretest = pd.read_csv('D:/Data/tmlcc-2021/test_set_clean_04-10.csv')
df_feat_pretest = pd.read_csv('D:/Code/tcml/test_mnc_metal.csv')

In [3]:
len(df_train.columns)

26

In [4]:
len(df_pretest.columns)

24

In [5]:
df_fix = pd.read_csv('D:/Data/tmlcc-2021/sra_2to15.csv')
df_fix_train = df_fix[df_fix['flag']=='train']
df_fix_test = df_fix[df_fix['flag']=='test']

In [6]:
df_fix_train

,MOFname,metal_linker,organic_linker1,organic_linker2,topology,flag
0,mof_unit_43,9,15,25,sra,train
1,mof_unit_51,9,12,15,sra,train
2,mof_unit_69,9,15,2,sra,train
3,mof_unit_100,9,12,15,sra,train
4,mof_unit_165,9,11,15,sra,train
...,...,...,...,...,...,...
1113,mof_unit_68469,9,15,22,sra,train
1114,mof_unit_68473,9,15,22,sra,train
1115,mof_unit_68515,9,15,22,sra,train
1116,mof_unit_68566,9,5,15,sra,train
1117,mof_unit_68595,9,15,22,sra,train

In [7]:
for i in range(len(df_fix_train)):
    name = df_fix_train.iloc[i]['MOFname']
    idx = df_train.loc[df_train['MOFname']==name].index.item()
    
    df_train.at[idx,'metal_linker'] = df_fix_train.iloc[i]['metal_linker']
    df_train.at[idx,'organic_linker1'] = df_fix_train.iloc[i]['organic_linker1']
    df_train.at[idx,'organic_linker2'] = df_fix_train.iloc[i]['organic_linker2']

In [8]:
for i in range(len(df_fix_test)):
    name = df_fix_test.iloc[i]['MOFname']
    idx = df_pretest.loc[df_pretest['MOFname']==name].index.item()
    
    df_pretest.at[idx,'metal_linker'] = df_fix_test.iloc[i]['metal_linker']
    df_pretest.at[idx,'organic_linker1'] = df_fix_test.iloc[i]['organic_linker1']
    df_pretest.at[idx,'organic_linker2'] = df_fix_test.iloc[i]['organic_linker2']

## surface area = 0

In [9]:
df_train['surface_area [m^2/g]'].replace(0,np.nan,inplace = True)
df_train.dropna(inplace = True)
df_train.reset_index(drop = True,inplace = True)

In [10]:
df_train

,MOFname,volume [A^3],weight [u],density [g/cm3],Di-LCD [A],Df-PLD [A],Dif [A],surface_area [m^2/g],void_volume [cm^3/g],calc_void fraction,...,CO2/N2_selectivity,heat_adsorption_CO2_P0.15bar_T298K [kcal/mol],imp heat_adsorption,_cell_length_a,_cell_length_b,_cell_length_c,_cell_angle_alpha,_cell_angle_beta,_cell_angle_gamma,CO2_working_capacity [mL/g]
0,mof_unit_2,2769.503842,2211.697211,1.326058,7.31755,6.28759,7.31755,603.61,0.1040,0.137910,...,33.616780,7.147286,7.147286,8.463295,17.684225,18.960098,100.063446,91.815775,96.942210,101.224774
1,mof_unit_3,1089.818728,773.687960,1.178828,6.73435,4.65130,6.73435,788.50,0.1262,0.148768,...,19.263726,6.347967,6.347967,10.732110,9.552271,10.631996,89.202223,89.943258,90.387501,118.987011
2,mof_unit_4,2205.198301,1304.638720,0.982384,6.32917,5.77752,6.32917,1441.53,0.2220,0.218089,...,25.701377,6.190085,6.190085,6.935530,17.504896,19.274980,109.537419,90.234580,90.532988,187.626004
3,mof_unit_6,3954.659761,1543.027680,0.647893,12.20304,11.77350,12.20304,2430.55,0.5725,0.370919,...,17.146541,5.398304,5.398304,24.949291,7.054011,22.606019,90.036873,96.274104,89.946334,55.786959
4,mof_unit_7,3565.914939,1954.749656,0.910247,12.00479,10.98421,12.00316,1530.02,0.3662,0.333332,...,18.363791,6.303857,6.303857,8.286700,19.200319,22.787351,100.168180,89.967715,92.229090,111.690462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56732,mof_unit_66520,1426.479810,1272.451540,1.481203,6.86894,5.52882,6.86894,1343.62,0.2038,0.301869,...,5.867674,4.485481,4.485481,10.277785,10.671366,13.626838,93.277966,74.428678,97.667494,7.602105
56733,mof_unit_66521,23943.701366,5497.752320,0.381270,19.22726,16.68686,18.97525,4182.24,1.7399,0.663372,...,4.060772,3.605688,3.605688,25.892701,43.014841,25.102146,89.999427,121.083481,90.000229,2.675231
56734,mof_unit_66522,14389.971556,4396.164320,0.507286,12.90542,9.32427,12.90509,4149.64,1.1246,0.570494,...,4.313411,3.361233,3.361233,26.397988,33.011322,21.131416,89.999962,128.607067,90.000014,-1.686092
56735,mof_unit_66523,16997.806645,3932.703680,0.384182,13.60306,11.22574,13.60306,4326.62,1.7430,0.669630,...,3.447440,2.781566,2.781566,30.481473,30.370459,18.361391,90.000000,89.999989,90.000000,-7.546805
56736,mof_unit_66524,7391.212513,2142.468600,0.481324,15.53418,7.38431,15.53418,3835.28,1.0905,0.524884,...,4.943257,3.804150,3.804150,21.530692,21.567014,22.159299,119.218130,120.250132,89.030490,4.587312

In [11]:
# na_free = df_train['heat_adsorption_CO2_P0.15bar_T298K [kcal/mol]'].dropna()
# only_na = df_train[~df_train.index.isin(na_free.index)]

## mnc metal

In [13]:
df_train = df_train.join(df_feat_train)
df_pretest = df_pretest.join(df_feat_pretest)

## mnc functional

In [15]:
df_feat_train_1 = pd.read_csv('D:/Code/tcml/train_mnc_fg_1.csv')
df_feat_pretest_1 = pd.read_csv('D:/Code/tcml/test_mnc_fg_1.csv')

In [16]:
df_train = df_train.join(df_feat_train_1)
df_pretest = df_pretest.join(df_feat_pretest_1)

In [17]:
df_train['num_fgs_all'] = df_train['mnc_fg-1']+df_train['mnc_fg-2']
df_train['mnc_fgs_all'] = [min(x,y) for x,y in zip(df_train['num_fg-1'].tolist(),df_train['num_fg-2'].tolist())]
df_pretest['num_fgs_all'] = df_pretest['mnc_fg-1']+df_pretest['mnc_fg-2']
df_pretest['mnc_fgs_all'] = [min(x,y) for x,y in zip(df_pretest['num_fg-1'].tolist(),df_pretest['num_fg-2'].tolist())]

## remove useless columns (noise)

In [19]:
df_train.drop(columns = ['imp heat_adsorption','num_fg-1', 'mnc_fg-1', 'num_fg-2', 'mnc_fg-2'],inplace = True)
df_pretest.drop(columns = ['num_fg-1', 'mnc_fg-1', 'num_fg-2', 'mnc_fg-2'],inplace = True)

In [20]:
df_train

,MOFname,volume [A^3],weight [u],density [g/cm3],Di-LCD [A],Df-PLD [A],Dif [A],surface_area [m^2/g],void_volume [cm^3/g],calc_void fraction,...,_cell_length_b,_cell_length_c,_cell_angle_alpha,_cell_angle_beta,_cell_angle_gamma,CO2_working_capacity [mL/g],num_metal,mnc_metal,num_fgs_all,mnc_fgs_all
0,mof_unit_2,2769.503842,2211.697211,1.326058,7.31755,6.28759,7.31755,603.61,0.1040,0.137910,...,17.684225,18.960098,100.063446,91.815775,96.942210,101.224774,2,1.204092,22,-0.701340
1,mof_unit_3,1089.818728,773.687960,1.178828,6.73435,4.65130,6.73435,788.50,0.1262,0.148768,...,9.552271,10.631996,89.202223,89.943258,90.387501,118.987011,2,0.946149,4,-0.790911
2,mof_unit_4,2205.198301,1304.638720,0.982384,6.32917,5.77752,6.32917,1441.53,0.2220,0.218089,...,17.504896,19.274980,109.537419,90.234580,90.532988,187.626004,4,1.411146,28,-0.531874
3,mof_unit_6,3954.659761,1543.027680,0.647893,12.20304,11.77350,12.20304,2430.55,0.5725,0.370919,...,7.054011,22.606019,90.036873,96.274104,89.946334,55.786959,4,1.193537,6,-0.915682
4,mof_unit_7,3565.914939,1954.749656,0.910247,12.00479,10.98421,12.00316,1530.02,0.3662,0.333332,...,19.200319,22.787351,100.168180,89.967715,92.229090,111.690462,2,1.641523,64,-0.479647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56732,mof_unit_66520,1426.479810,1272.451540,1.481203,6.86894,5.52882,6.86894,1343.62,0.2038,0.301869,...,10.671366,13.626838,93.277966,74.428678,97.667494,7.602105,2,1.025893,8,-0.831288
56733,mof_unit_66521,23943.701366,5497.752320,0.381270,19.22726,16.68686,18.97525,4182.24,1.7399,0.663372,...,43.014841,25.102146,89.999427,121.083481,90.000229,2.675231,16,0.971793,24,-0.807710
56734,mof_unit_66522,14389.971556,4396.164320,0.507286,12.90542,9.32427,12.90509,4149.64,1.1246,0.570494,...,33.011322,21.131416,89.999962,128.607067,90.000014,-1.686092,16,1.010950,16,-0.931989
56735,mof_unit_66523,16997.806645,3932.703680,0.384182,13.60306,11.22574,13.60306,4326.62,1.7430,0.669630,...,30.370459,18.361391,90.000000,89.999989,90.000000,-7.546805,12,1.020954,64,-0.260233
56736,mof_unit_66524,7391.212513,2142.468600,0.481324,15.53418,7.38431,15.53418,3835.28,1.0905,0.524884,...,21.567014,22.159299,119.218130,120.250132,89.030490,4.587312,6,0.920058,34,-0.904349

## bag of word functional group , one-hot topology

### topology

In [21]:
enc_topology = OneHotEncoder(handle_unknown='ignore')

In [22]:
enc_topology.fit(df_train[['topology']].values)

OneHotEncoder(handle_unknown='ignore')

In [23]:
enc_topology.categories_

[array(['acs', 'bcu', 'etb', 'fof', 'nbo', 'pcu', 'pts', 'rht', 'sra',
        'tbo', 'the'], dtype=object)]

### train

In [24]:
train_topology = enc_topology.transform(df_train[['topology']].values).toarray()
df_train_topology = pd.DataFrame(train_topology,columns = enc_topology.categories_)

### pretest

In [25]:
pretest_topology = enc_topology.transform(df_pretest[['topology']].values).toarray()
df_pretest_topology = pd.DataFrame(pretest_topology,columns = enc_topology.categories_)

In [26]:
df_train_topology

       acs  bcu  etb  fof  nbo  pcu  pts  rht  sra  tbo  the
0      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
56732  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
56733  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
56734  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
56735  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
56736  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0

[56737 rows x 11 columns]

### bag of word functional group

In [27]:
enc_func = OneHotEncoder(handle_unknown='ignore')

In [28]:
enc_func.fit(df_train[['functional_groups 1']].values)
enc_func.categories_

[array(['Br', 'CN', 'COOH', 'Cl', 'Et', 'F', 'H', 'HCO', 'I', 'Me', 'NH2',
        'NHMe', 'NO2', 'OEt', 'OH', 'OMe', 'OPr', 'Ph', 'Pr', 'SO3H'],
       dtype=object)]

### train

In [29]:
train_func_1 = enc_func.transform(df_train[['functional_groups 1']].values).toarray()
train_func_2 = enc_func.transform(df_train[['functional_groups 2']].values).toarray()
train_func = train_func_1+train_func_2
df_train_func = pd.DataFrame(train_func,columns = enc_func.categories_)

In [30]:
df_train_func

,Br,CN,COOH,Cl,Et,F,H,HCO,I,Me,NH2,NHMe,NO2,OEt,OH,OMe,OPr,Ph,Pr,SO3H
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56732,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56733,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56734,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
56735,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56736,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
pretest_func_1 = enc_func.transform(df_pretest[['functional_groups 1']].values).toarray()
pretest_func_2 = enc_func.transform(df_pretest[['functional_groups 2']].values).toarray()
pretest_func = pretest_func_1+pretest_func_2
df_pretest_func = pd.DataFrame(pretest_func,columns = enc_func.categories_)

In [32]:
df_pretest_func

,Br,CN,COOH,Cl,Et,F,H,HCO,I,Me,NH2,NHMe,NO2,OEt,OH,OMe,OPr,Ph,Pr,SO3H
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
16996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16997,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
16999,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

## join everything

In [33]:
df_train = df_train.reset_index(drop = True).join(df_train_topology)
df_train = df_train.join(df_train_func)
#df_train = pd.concat([df_train,df_train_topology,df_train_func],ignore_index=True,axis = 1)

In [34]:
df_pretest = df_pretest.join(df_pretest_topology)
df_pretest = df_pretest.join(df_pretest_func)

In [35]:
df_train

,MOFname,volume [A^3],weight [u],density [g/cm3],Di-LCD [A],Df-PLD [A],Dif [A],surface_area [m^2/g],void_volume [cm^3/g],calc_void fraction,...,"(NH2,)","(NHMe,)","(NO2,)","(OEt,)","(OH,)","(OMe,)","(OPr,)","(Ph,)","(Pr,)","(SO3H,)"
0,mof_unit_2,2769.503842,2211.697211,1.326058,7.31755,6.28759,7.31755,603.61,0.1040,0.137910,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,mof_unit_3,1089.818728,773.687960,1.178828,6.73435,4.65130,6.73435,788.50,0.1262,0.148768,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,mof_unit_4,2205.198301,1304.638720,0.982384,6.32917,5.77752,6.32917,1441.53,0.2220,0.218089,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,mof_unit_6,3954.659761,1543.027680,0.647893,12.20304,11.77350,12.20304,2430.55,0.5725,0.370919,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,mof_unit_7,3565.914939,1954.749656,0.910247,12.00479,10.98421,12.00316,1530.02,0.3662,0.333332,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56732,mof_unit_66520,1426.479810,1272.451540,1.481203,6.86894,5.52882,6.86894,1343.62,0.2038,0.301869,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56733,mof_unit_66521,23943.701366,5497.752320,0.381270,19.22726,16.68686,18.97525,4182.24,1.7399,0.663372,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56734,mof_unit_66522,14389.971556,4396.164320,0.507286,12.90542,9.32427,12.90509,4149.64,1.1246,0.570494,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
56735,mof_unit_66523,16997.806645,3932.703680,0.384182,13.60306,11.22574,13.60306,4326.62,1.7430,0.669630,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56736,mof_unit_66524,7391.212513,2142.468600,0.481324,15.53418,7.38431,15.53418,3835.28,1.0905,0.524884,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## drop func , topology

In [36]:
df_train.drop(columns = ['topology','functional_groups 1','functional_groups 2'],inplace = True)
df_pretest.drop(columns = ['topology','functional_groups 1','functional_groups 2'],inplace = True)

# normalize

## scaler sklearn (z score) (2)

In [37]:
target_train = [col for col in df_train.columns if col not in ['CO2_working_capacity [mL/g]','MOFname']]
target_pretest = [col for col in df_pretest.columns if col not in ['MOFname']]

In [38]:
for i in range(len(target_train)):
    x_train = df_train[[target_train[i]]].values
    x_pretest = df_pretest[[target_pretest[i]]].values
    
    scaler = StandardScaler()    
    scaler.fit(x_train)
    x_train = scaler.transform(x_train)
    x_pretest = scaler.transform(x_pretest)
    
    df_train[target_train[i]] = list(x_train.squeeze(1))
    df_pretest[target_pretest[i]] = list(x_pretest.squeeze(1))

In [39]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56737 entries, 0 to 56736
Data columns (total 57 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   MOFname                                        56737 non-null  object
 1   volume [A^3]                                   56737 non-null  float64
 2   weight [u]                                     56737 non-null  float64
 3   density [g/cm3]                                56737 non-null  float64
 4   Di-LCD [A]                                     56737 non-null  float64
 5   Df-PLD [A]                                     56737 non-null  float64
 6   Dif [A]                                        56737 non-null  float64
 7   surface_area [m^2/g]                           56737 non-null  float64
 8   void_volume [cm^3/g]                           56737 non-null  float64
 9   calc_void fraction                             56737 non-null  float64
 10  metal_linker                                   56737 non-null  float64
 11  organic_linker1                                56737 non-null  float64
 12  organic_linker2                                56737 non-null  float64
 13  CO2/N2_selectivity                             56737 non-null  float64
 14  heat_adsorption_CO2_P0.15bar_T298K [kcal/mol]  56737 non-null  float64
 15  _cell_length_a                                 56737 non-null  float64
 16  _cell_length_b                                 56737 non-null  float64
 17  _cell_length_c                                 56737 non-null  float64
 18  _cell_angle_alpha                              56737 non-null  float64
 19  _cell_angle_beta                               56737 non-null  float64
 20  _cell_angle_gamma                              56737 non-null  float64
 21  CO2_working_capacity [mL/g]                    56737 non-null  float64
 22  num_metal                                      56737 non-null  float64
 23  mnc_metal                                      56737 non-null  float64
 24  num_fgs_all                                    56737 non-null  float64
 25  mnc_fgs_all                                    56737 non-null  float64
 26  (acs,)                                         56737 non-null  float64
 27  (bcu,)                                         56737 non-null  float64
 28  (etb,)                                         56737 non-null  float64
 29  (fof,)                                         56737 non-null  float64
 30  (nbo,)                                         56737 non-null  float64
 31  (pcu,)                                         56737 non-null  float64
 32  (pts,)                                         56737 non-null  float64
 33  (rht,)                                         56737 non-null  float64
 34  (sra,)                                         56737 non-null  float64
 35  (tbo,)                                         56737 non-null  float64
 36  (the,)                                         56737 non-null  float64
 37  (Br,)                                          56737 non-null  float64
 38  (CN,)                                          56737 non-null  float64
 39  (COOH,)                                        56737 non-null  float64
 40  (Cl,)                                          56737 non-null  float64
 41  (Et,)                                          56737 non-null  float64
 42  (F,)                                           56737 non-null  float64
 43  (H,)                                           56737 non-null  float64
 44  (HCO,)                                         56737 non-null  float64
 45  (I,)                                           56737 non-null  float64
 46  (Me,)                                          56737 non-null  float64
 47  (NH2,)                                         56737 non-null  float64
 48  (NHMe,)                                        56737 non-null  float64
 49  (NO2,)                                         56737 non-null  float64
 50  (OEt,)                                         56737 non-null  float64
 51  (OH,)                                          56737 non-null  float64
 52  (OMe,)                                         56737 non-null  float64
 53  (OPr,)                                         56737 non-null  float64
 54  (Ph,)                                          56737 non-null  float64
 55  (Pr,)                                          56737 non-null  float64
 56  (SO3H,)                                        56737 non-null  float64
dtypes: float64(56), object(1)
memory usage: 24.7+ MB

In [40]:
df_train

,MOFname,volume [A^3],weight [u],density [g/cm3],Di-LCD [A],Df-PLD [A],Dif [A],surface_area [m^2/g],void_volume [cm^3/g],calc_void fraction,...,"(NH2,)","(NHMe,)","(NO2,)","(OEt,)","(OH,)","(OMe,)","(OPr,)","(Ph,)","(Pr,)","(SO3H,)"
0,mof_unit_2,-0.196623,0.439532,1.476494,-0.299480,0.095003,-0.269242,-1.208092,-0.688206,-1.104379,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,2.914199,-0.289377,-0.213389,-0.244968,-0.301334
1,mof_unit_3,-0.542950,-0.694223,0.953737,-0.485361,-0.613211,-0.455009,-1.053790,-0.642881,-1.030173,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,2.914199,-0.289377,-0.213389,-0.244968,-0.301334
2,mof_unit_4,-0.312975,-0.275611,0.256243,-0.614502,-0.125764,-0.584072,-0.508798,-0.447288,-0.556417,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,3.318571
3,mof_unit_6,0.047739,-0.087660,-0.931405,1.257649,2.469399,1.286943,0.316597,0.268323,0.488050,...,-0.315522,-0.29052,2.761151,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,4.082165,-0.301334
4,mof_unit_7,-0.032415,0.236950,0.000109,1.194462,2.127781,1.223275,-0.434948,-0.152877,0.231176,...,3.169349,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56732,mof_unit_66520,-0.473535,-0.300988,2.027352,-0.442463,-0.233405,-0.412138,-0.590510,-0.484446,0.016150,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
56733,mof_unit_66521,4.169185,3.030324,-1.878080,3.496445,4.595985,3.444108,1.778484,2.651785,2.486733,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
56734,mof_unit_66522,2.199346,2.161810,-1.430647,1.481515,1.409331,1.510568,1.751278,1.395537,1.851985,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,3.455696,-0.213389,-0.244968,-0.301334
56735,mof_unit_66523,2.737044,1.796408,-1.867740,1.703870,2.232319,1.732894,1.898978,2.658114,2.529499,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
56736,mof_unit_66524,0.756305,0.384951,-1.522827,2.319367,0.569683,2.348017,1.488926,1.325915,1.540279,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334

In [41]:
df_pretest

,MOFname,volume [A^3],weight [u],density [g/cm3],Di-LCD [A],Df-PLD [A],Dif [A],surface_area [m^2/g],void_volume [cm^3/g],calc_void fraction,...,"(NH2,)","(NHMe,)","(NO2,)","(OEt,)","(OH,)","(OMe,)","(OPr,)","(Ph,)","(Pr,)","(SO3H,)"
0,mof_unit_68614,-0.518520,-0.675284,0.660523,-1.084491,-0.983862,-1.074299,-1.222338,-0.688411,-1.268468,...,-0.315522,-0.29052,-0.362168,3.622252,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
1,mof_unit_68615,0.083152,1.639476,2.102799,-0.466715,-0.322275,-0.517470,-1.000387,-0.610214,-0.586766,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
2,mof_unit_68616,-0.437315,-0.715098,-0.482142,-0.518635,-0.576941,-0.488264,0.921802,-0.007305,0.268617,...,-0.315522,-0.29052,-0.362168,-0.276071,2.697094,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
3,mof_unit_68617,-0.265257,-0.519104,-0.822329,-0.223949,-0.112688,-0.193756,1.226716,0.316915,0.718625,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,2.914199,-0.289377,-0.213389,-0.244968,-0.301334
4,mof_unit_68618,-0.123651,-0.249672,-0.707074,0.525588,0.660380,0.555326,0.523492,0.218097,0.615704,...,-0.315522,-0.29052,2.761151,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,4.082165,-0.301334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,mof_unit_85609,5.966552,2.420032,-2.379126,3.321171,3.727802,3.344073,3.061952,5.697774,3.257355,...,-0.315522,-0.29052,2.761151,-0.276071,2.697094,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
16996,mof_unit_85610,0.277911,-0.122268,-1.488858,2.094127,1.479754,2.092437,1.640816,1.561321,1.998395,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,2.914199,-0.289377,-0.213389,-0.244968,-0.301334
16997,mof_unit_85611,0.195191,-0.261884,-1.562690,1.991520,0.910033,2.020280,1.867382,1.485983,1.708487,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
16998,mof_unit_85612,0.197730,-0.347457,-1.703752,2.033273,1.823731,2.061339,1.903351,1.976396,2.097593,...,-0.315522,-0.29052,-0.362168,-0.276071,2.697094,-0.343147,-0.289377,-0.213389,-0.244968,-0.301334
16999,mof_unit_85613,4.531850,2.474854,-2.132331,3.493605,3.095642,3.521543,2.466286,3.828612,2.855090,...,-0.315522,-0.29052,-0.362168,-0.276071,-0.370769,2.914199,-0.289377,-0.213389,-0.244968,-0.301334

In [42]:
# df_train.to_csv('train_10-10-v2.csv',index = False)
# df_pretest.to_csv('test_10-10-v2.csv',index = False)